const PM_SENSE_SPACE_ID = '7663472168944012468';
const PM_SENSE_PARENT_NODE_TOKEN = 'Nv3JwfP0RiqYUWk3KjgcTD6wnnd';
const PM_SENSE_PARENT_URL =
  `https://my.feishu.cn/wiki/${PM_SENSE_PARENT_NODE_TOKEN}`;

export {
  PM_SENSE_PARENT_NODE_TOKEN,
  PM_SENSE_PARENT_URL,
  PM_SENSE_SPACE_ID,
};
